# -*- coding: utf-8 -*-
"""CONVERT_IMAGE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nQgkpjhCYFJRzLh4ztMw-GkXLkYXI98l
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import skimage
from skimage.io import imread

def show(image: np.ndarray, title="Image", cmap_type="gray", axis=False) :
  plt.imshow(image, cmap=cmap_type)
  plt.title(title)
  if not axis : 
    plt.axis("off")
  plt.margins(0,0)
  plt.show()

def compare(original, filtered, title_filtered="Filtered", 
            cmap_type="gray",axis=False,title_original="origin"):
  fig, (ax1, ax2) = plt.subplots(ncols=2, figsize=(10,8), sharex=True, sharey=True)
  ax1.imshow(original, cmap=cmap_type)
  ax1.set_title(title_original)
  ax2.imshow(filtered, cmap=cmap_type)
  ax2.set_title(title_filtered)

  if not axis : 
    ax1.axis("off")
    ax2.axis("off")
  plt.subplots_adjust(top=1, bottom=0, right=1, left=0, hspace = 0, wspace=0.01)
  plt.margins(0,0)
  plt.show()
  plt.savefig('test.png')
  
#warnings.filterwarnings("ignore")
image = imread("가위바위보.jpg")
show(image, title="가위", axis=True)

from PIL import Image
im = Image.open("가위바위보.jpg")
im

im.thumbnail((512,512))
im.save("test.png","png")
im